version: 1
formatters:
  simpleFormatter:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  consoleHandler:
    class: logging.StreamHandler
    formatter: simpleFormatter
    level: DEBUG

loggers:
  AIManager:
    level: DEBUG
    handlers: [consoleHandler]
    propagate: False
  AudioManager:
    level: DEBUG
    handlers: [consoleHandler]
    propagate: False
  GoogleDriveClient:
    level: DEBUG
    handlers: [consoleHandler]
    propagate: False
  MainController:
    level: DEBUG
    handlers: [consoleHandler]
    propagate: False
  SheetManager:
    level: DEBUG
    handlers: [consoleHandler]
    propagate: False
  Transcriber:
    level: DEBUG
    handlers: [consoleHandler]
    propagate: False

root:
  level: INFO
  handlers: [consoleHandler]
